// <auto-generated />
namespace CodeFApp.Data.Migrations.MySqlServerMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_code_department_table_mySql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_code_department_table_mySql));
        
        string IMigrationMetadata.Id
        {
            get { return "202212100847485_Add_code_department_table_mySql"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
